#=--------------------------- MAIN CONFIGURATION ----------------------------=#
server:
  context-path: /qoantum/phonebook

spring:
  profiles:
    active: TEST
---
#=--------------------------- DEV CONFIGURATION -----------------------------=#
spring:
  profiles: DEV
#  jpa:
#    database: H2
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create-drop
#  datasource:
#      url: "jdbc:postgresql://localhost/qoantum?characterEncoding=UTF-8&currentSchema=public&searchpath=public"
#      username: postgres
#      password: '@postgres!'
server:
  port: 7070

---
#=--------------------------- TEST CONFIGURATION -----------------------------=#
spring:
  profiles: TEST
  jpa:
    properties:
      hibernate:
        default_schema: phonebook
    database: POSTGRESQL
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: "jdbc:postgresql://localhost/qoantum?characterEncoding=UTF-8&currentSchema=phonebook&searchpath=phonebook"
    username: postgres
    password: '@postgres!'
  data:
    elasticsearch:
      cluster-name: local-node
      cluster-nodes: 192.168.0.10:9300

server:
  port: 7070

---
#=--------------------------- PROD CONFIGURATION -----------------------------=#
spring:
  profiles: PROD