
-- Dummy Users --
INSERT INTO T_USER (ID, FIRST_NAME, LAST_NAME, USERNAME, START_OF_USE, PASSWORD, EMAIL, DATE_OF_BIRTH, RECORD_STATUS) VALUES (NEXTVAL('USER_SEQ'), 'FIRST_NAME_1', 'LAST_NAME_1', 'USERNAME_1', '2016-01-15 01:15:45', 'PASSWORD_1', 'EMAIL_1@QOANTUM.COM', '2016-01-15 01:15:45', 'ACTIVE');
INSERT INTO T_USER (ID, FIRST_NAME, LAST_NAME, USERNAME, START_OF_USE, PASSWORD, EMAIL, DATE_OF_BIRTH, RECORD_STATUS) VALUES (NEXTVAL('USER_SEQ'), 'FIRST_NAME_2', 'LAST_NAME_2', 'USERNAME_2', '2016-01-15 01:15:45', 'PASSWORD_2', 'EMAIL_2@QOANTUM.COM', '2016-01-15 01:15:45', 'ACTIVE');
INSERT INTO T_USER (ID, FIRST_NAME, LAST_NAME, USERNAME, START_OF_USE, PASSWORD, EMAIL, DATE_OF_BIRTH, RECORD_STATUS) VALUES (NEXTVAL('USER_SEQ'), 'FIRST_NAME_3', 'LAST_NAME_3', 'USERNAME_3', '2016-01-15 01:15:45', 'PASSWORD_3', 'EMAIL_3@QOANTUM.COM', '2016-01-15 01:15:45', 'ACTIVE');

-- Dummy Roles --
INSERT INTO T_ROLE (ID, NAME, RECORD_STATUS) VALUES (NEXTVAL('ROLE_SEQ'), 'USER', 'ACTIVE');
INSERT INTO T_ROLE (ID, NAME, RECORD_STATUS) VALUES (NEXTVAL('ROLE_SEQ'), 'LOCAL_ADMIN', 'ACTIVE');
INSERT INTO T_ROLE (ID, NAME, RECORD_STATUS) VALUES (NEXTVAL('ROLE_SEQ'), 'ADMIN', 'ACTIVE');

-- Dummy User Admin Roles --
INSERT INTO T_USER_ROLE(ID, USER_ID, ROLE_ID, RECORD_STATUS) VALUES (NEXTVAL('USERROLE_SEQ'), 1, 1, 'ACTIVE');
INSERT INTO T_USER_ROLE(ID, USER_ID, ROLE_ID, RECORD_STATUS) VALUES (NEXTVAL('USERROLE_SEQ'), 1, 2, 'ACTIVE');
INSERT INTO T_USER_ROLE(ID, USER_ID, ROLE_ID, RECORD_STATUS) VALUES (NEXTVAL('USERROLE_SEQ'), 1, 3, 'ACTIVE');

-- Dummy User Local Admin Roles --
INSERT INTO T_USER_ROLE(ID, USER_ID, ROLE_ID, RECORD_STATUS) VALUES (NEXTVAL('USERROLE_SEQ'), 2, 1, 'ACTIVE');
INSERT INTO T_USER_ROLE(ID, USER_ID, ROLE_ID, RECORD_STATUS) VALUES (NEXTVAL('USERROLE_SEQ'), 2, 2, 'ACTIVE');

-- Dummy User Roles --
INSERT INTO T_USER_ROLE(ID, USER_ID, ROLE_ID, RECORD_STATUS) VALUES (NEXTVAL('USERROLE_SEQ'), 3, 1, 'ACTIVE');

-- Dummy Groups --
INSERT INTO T_GROUP (ID, NAME, RECORD_STATUS) VALUES (NEXTVAL('GROUP_SEQ'), 'USER_GROUP', 'ACTIVE');
INSERT INTO T_GROUP (ID, NAME, RECORD_STATUS) VALUES (NEXTVAL('GROUP_SEQ'), 'ADMIN_GROUP', 'ACTIVE');
INSERT INTO T_GROUP (ID, NAME, RECORD_STATUS) VALUES (NEXTVAL('GROUP_SEQ'), 'LOCAL_ADMIN_GROUP', 'ACTIVE');

-- Dummy Group Members --
INSERT INTO T_GROUP_MEMBER(ID, GROUP_ID, USER_ID, RECORD_STATUS) VALUES (NEXTVAL('GROUPMEMBER_SEQ'), 1, 1, 'ACTIVE');
INSERT INTO T_GROUP_MEMBER(ID, GROUP_ID, USER_ID, RECORD_STATUS) VALUES (NEXTVAL('GROUPMEMBER_SEQ'), 2, 2, 'ACTIVE');
INSERT INTO T_GROUP_MEMBER(ID, GROUP_ID, USER_ID, RECORD_STATUS) VALUES (NEXTVAL('GROUPMEMBER_SEQ'), 3, 3, 'ACTIVE');